### ISSUE TITLE
Error occurred while enabling

### ISSUE THREAD

**Issue by DejVIIK-Original** [Slimefun-Addon-Community/LiteXpansion#92] opened 2024-02-13 18:54 UTC
## Server Log
[Server thread/ERROR]: Error occurred while enabling LiteXpansion vDEV - 192 (git 661862ed) (Is it up to date?)
java.lang.NoSuchMethodError: 'boolean org.bukkit.enchantments.Enchantment.isAcceptingRegistrations()'
	at dev.j3fftw.litexpansion.LiteXpansion.registerEnchantments(LiteXpansion.java:68) ~[LiteXpansion - DEV 192 (git 66186).jar:?]
	at dev.j3fftw.litexpansion.LiteXpansion.onEnable(LiteXpansion.java:43) ~[LiteXpansion - DEV 192 (git 66186).jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[purpur-1.20.4.jar:git-Purpur-2141]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.4.jar:git-Purpur-2141]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:653) ~[purpur-1.20.4.jar:git-Purpur-2141]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:564) ~[purpur-1.20.4.jar:git-Purpur-2141]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[purpur-1.20.4.jar:git-Purpur-2141]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[purpur-1.20.4.jar:git-Purpur-2141]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:346) ~[purpur-1.20.4.jar:git-Purpur-2141]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1146) ~[purpur-1.20.4.jar:git-Purpur-2141]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2141]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]

 - Server Software (Spigot/Paper):
 - Minecraft version: 1.20.4 (Purpur-2141)
 - Slimefun version: Slimefun4 - DEV 1104 (git c9774)
 - LiteXpansion version: 192 (git 661862ed)

**Comment by Boomer-1** [comment] 2024-02-13 18:57
this is a duplicate of the previously reported issue

**Closed as not planned** 2024-02-13 19:02 UTC
Labels: bug
