### ISSUE TITLE
[BUG] Iron Golem creation from iron block based blocks

### ISSUE THREAD

**Issue by andris155** [Slimefun-Addon-Community/LiteXpansion#31] opened 2021-02-22 16:24 UTC
## Description (REQUIRED)

The Iron Golem creation works from MFE, Generator, and Machine Block.

## Steps to reproduce the Issue (REQUIRED)

1. Build Iron Golem from iron block based block and Curved Pumpkin.

## Expected behavior (REQUIRED)

Iron Golem creation not work from LiteXpansion iron block based blocks.

## Environment (REQUIRED)

Purpur git-Purpur-982 (MC: 1.16.5)
Slimefun DEV - 819 (git 854c3335)
Metrics-Module #21
Java 11

Backwards compatibility enabled!

Installed Addons: (1)
  LiteXpansion vDEV - 134 (git 579fd4e7)

**Comment by TheBusyBiscuit** [comment] 2021-02-22 17:25
Duplicate of Slimefun/Slimefun4#2425

**Closed as completed** 2021-02-22 17:43 UTC
Labels: bug
