### ISSUE TITLE
[BUG] LiteXpansion no loading with latest Slimefun

### ISSUE THREAD

**Issue by andris155** [Slimefun-Addon-Community/LiteXpansion#15] opened 2021-01-13 21:50 UTC
## Description (REQUIRED)

LiteXpansion no loading with latest Slimefun.

## Steps to reproduce the Issue (REQUIRED)

Start server with latest Slimefun and LiteXpansion add-on

## Expected behavior (REQUIRED)

LiteXpansion works perfectly with latest Slimefun.

## Server Log

https://pastebin.com/XDVfmAtf

## Environment (REQUIRED)

 - Server Software (Spigot/Paper): Yatopia
 - Minecraft version: 1.16.4
 - CS-CoreLib version: CS-CoreLib vDEV - 92 (git e9150d72)
 - Slimefun version: Slimefun vDEV - 783 (git d8004510)
 - LiteXpansion version: LiteXpansion vDEV - 118 (git 12f8d64e)

**Comment by TheBusyBiscuit** [comment] 2021-01-14 01:51
Also experienced this issue, I already made a report about it earlier: #14

**Comment by MinecraftAdmin** [comment] 2021-01-14 03:45
Can confirm, does not work for us either.

**Comment by J3fftw1** [comment] 2021-01-14 16:12
duplicate of #14

**Closed as completed by J3fftw1** 2021-01-14 16:12 UTC
Labels: bug
