### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by Boomer-1** [Slimefun-Addon-Community/LiteXpansion#17] opened 2021-01-15 01:53 UTC
## Description (REQUIRED)

As my server was loading I saw that lite expansion threw warnings / errors into the console that I thought you would want to know about. Also the slimefun addon page does not bring you here. the link is wrong. I could only get here from the builds page.

## Steps to reproduce the Issue (REQUIRED)

I can't tell you as it happened as the server was loading

## Expected behavior (REQUIRED)

no idea.

## Server Log

[latest.log](https://github.com/Slimefun-Addon-Community/LiteXpansion/files/5817922/latest.log)

## Environment (REQUIRED)

 - Server Software (Spigot/Paper): spigot 1.16.3
 - Minecraft version: 1.16.3
 - CS-CoreLib version: 92
 - Slimefun version: 784
 - LiteXpansion version: 119

**Comment by WalshyDev** [comment] 2021-01-17 10:47
Duplicate of #16

**Closed as completed by WalshyDev** 2021-01-17 10:47 UTC
Labels: bug
